[build]
  base = "frontend"
  command = "npm run build -- --configuration production"
  publish = "dist/frontend/browser/browser"

[[redirects]]
  from = "/api/*"
  to = "https://shellotech.eu.org/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://shellotech.eu.org/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ka/*"
  to = "/ka/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
