[build]
  base = "frontend"
  command = "npm run build -- --configuration production"
  publish = "dist/frontend/browser/browser"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://shello-demo-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://shello-demo-api.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ka/*"
  to = "/shellotech/ka/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/shellotech/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/shellotech/index.html"
  status = 200
