apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: shello
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
