apiVersion: v1
kind: Secret
metadata:
  name: shello-secrets
  namespace: shello
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_32+_CHAR_SECRET"
  REFRESH_SECRET: "REPLACE_WITH_32+_CHAR_SECRET"
  REFRESH_TOKEN_HMAC_KEY: "REPLACE_WITH_32+_CHAR_SECRET"
  TWO_FACTOR_ENCRYPTION_KEY: "REPLACE_WITH_16+_CHAR_SECRET"
  GOOGLE_CLIENT_ID: "REPLACE_IF_USED"
  GOOGLE_CLIENT_SECRET: "REPLACE_IF_USED"
  GOOGLE_REDIRECT_URI: "https://shellotech.eu.org/api/v1/auth/google/callback"
  GOOGLE_ALLOWED_ORIGIN: "https://shellotech.eu.org"
  SUPER_ADMIN_EMAIL: "admin@shello.local"
  SUPER_ADMIN_PASSWORD: "REPLACE_ME"
  SUPER_ADMIN_PIN_CODE: "000001"
  SUPER_ADMIN_NAME: "Shello"
  SUPER_ADMIN_LAST_NAME: "Admin"
  ADMIN_RESET_PASSWORD: "REPLACE_ME"
  MONGO_INITDB_ROOT_USERNAME: "shello"
  MONGO_INITDB_ROOT_PASSWORD: "REPLACE_ME"
  MONGO_URI: "mongodb://shello:REPLACE_ME@mongo:27017/shello_db?authSource=admin"
