apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-data
  namespace: shello
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
